#!/bin/bash

# Script de compilação e execução do Sistema Integrado de Bioinformática
# Versão 2.0 - IA Melhorada

echo "=== Sistema Integrado de Bioinformática com Deep Learning ==="
echo "Versão 2.0 - IA Melhorada"
echo "=============================================================="

# Verificar se estamos no diretório correto
if [ ! -f "CMakeLists.txt" ]; then
    echo "Erro: Execute este script no diretório raiz do projeto (onde está o CMakeLists.txt)"
    exit 1
fi

# Função para verificar dependências
check_dependencies() {
    echo "Verificando dependências..."
    
    # Verificar CMake
    if ! command -v cmake &> /dev/null; then
        echo "Erro: CMake não está instalado. Instale com: sudo apt-get install cmake"
        exit 1
    fi
    
    # Verificar compilador C++
    if ! command -v g++ &> /dev/null; then
        echo "Erro: g++ não está instalado. Instale com: sudo apt-get install build-essential"
        exit 1
    fi
    
    # Verificar Eigen3
    if ! pkg-config --exists eigen3; then
        echo "Aviso: Eigen3 pode não estar instalado. Instale com: sudo apt-get install libeigen3-dev"
        echo "Continuando mesmo assim..."
    fi
    
    # Verificar Python (para integração)
    if ! command -v python3 &> /dev/null; then
        echo "Aviso: Python3 não encontrado. Algumas funcionalidades podem não funcionar."
        echo "Instale com: sudo apt-get install python3 python3-pip"
    fi
    
    echo "Verificação de dependências concluída."
}

# Função para compilar o projeto
compile_project() {
    echo "Iniciando compilação..."
    
    # Criar diretório de build se não existir
    if [ ! -d "build" ]; then
        mkdir build
        echo "Diretório build criado."
    fi
    
    # Entrar no diretório build
    cd build
    
    # Configurar com CMake
    echo "Configurando projeto com CMake..."
    if ! cmake .. -DCMAKE_BUILD_TYPE=Release; then
        echo "Erro na configuração do CMake!"
        exit 1
    fi
    
    # Compilar
    echo "Compilando projeto..."
    if ! make -j$(nproc); then
        echo "Erro na compilação!"
        exit 1
    fi
    
    echo "Compilação concluída com sucesso!"
    cd ..
}

# Função para configurar ambiente Python
setup_python_environment() {
    echo "Configurando ambiente Python..."
    
    # Criar diretório dados se não existir
    if [ ! -d "dados" ]; then
        mkdir -p dados/{modelos,treinamento,sequencias,resultados,datasets}
        echo "Estrutura de diretórios criada em ./dados/"
    fi
    
    # Copiar arquivos Python se existirem
    if [ -f "../ia_classi.py" ]; then
        cp ../ia_classi.py dados/
        echo "Arquivo ia_classi.py copiado."
    fi
    
    if [ -f "../sistema_principal.py" ]; then
        cp ../sistema_principal.py dados/
        echo "Arquivo sistema_principal.py copiado."
    fi
    
    # Instalar dependências Python se requirements.txt existir
    if [ -f "requirements.txt" ]; then
        echo "Instalando dependências Python..."
        pip3 install -r requirements.txt --user
    fi
}

# Função para executar exemplos
run_examples() {
    echo "Executando exemplos..."
    
    if [ ! -f "build/bioinformatics_example" ]; then
        echo "Erro: Executável bioinformatics_example não encontrado!"
        echo "Execute primeiro: ./build_and_run.sh --compile"
        exit 1
    fi
    
    # Criar arquivo FASTA de exemplo
    create_example_fasta
    
    # Executar exemplo principal
    echo "--- Executando exemplo de bioinformática ---"
    ./build/bioinformatics_example
    
    echo "Execução concluída!"
}

# Função para criar arquivo FASTA de exemplo
create_example_fasta() {
    FASTA_FILE="dados/exemplo_sequencias.fasta"
    
    if [ ! -f "$FASTA_FILE" ]; then
        echo "Criando arquivo FASTA de exemplo..."
        
        cat > "$FASTA_FILE" << 'EOF'
>sp|P04637|P53_HUMAN Cellular tumor antigen p53 OS=Homo sapiens OX=9606 GN=TP53 PE=1 SV=4
MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGP
DEAPRMPEAAPPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYQGSYGFRLGFLHSGTAK
SVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHE
RCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNS
SCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKGEPHHELP
PGSTKRALPNNTSSSPQPKKKPLDGEYFTLQIRGRERFEMFRELNEALELKDAQAGKEPG
GSRAHSSHLKSKKGQSTSRHKKLMFKTEGPDSD

>sp|P53350|PLK1_HUMAN Serine/threonine-protein kinase PLK1 OS=Homo sapiens OX=9606 GN=PLK1 PE=1 SV=3
MAPPPRNPYDSAGGAKYSASLKTEQEPELAASLAKTPVQHKLIPKQHPCDKVTHLLSSPT
AKKKPVDSVMEKKAAFVFTKDNILVYLGNSLHYLSNKPSCSLVLTAQVLPDDPVELVVRR
WKFGDDNVQFGDYIMEVDNFTQQLQKVKVLMFKVLPGASCTAQSFALLGEKVDSKNSQLS
LTPFLLMLHSPGASLFNKFSGVQSNFKLQIFNCLTNGRLTPDLILTCSPIEPKICFVKSV
NFLQLSSLFKGFSNNLTYQKMKLKEMWQCTDNFVVRNAKAIKSNHTKEKQVYRTQSWTFL
LMQTLNSQIPATPSGRTLHSTPLFVSSYMSLNELKRNCQNILQRAALPGECFNKSLLLRL
GNSQGFQGRCYTDDQHILELRSRLLCKSRFQTILTSFEELVQKVRQVLMYAHQMVQVEQV
DQCQKLVKHFPVHVRLQTQEFIHTVRKIQLERAILVRKQAQMVRGTSQTYLIHPLRKVQL
MLEHLHKTKQKQLRTKLKKVKQFQFQLNHCVFLGRSFGADNLVNHLLLTMPEFLEGWLV
TPGVGKGDLYIRESLSRRFEKDAFMNVKQMVYQVNHNTNQAPPDMRFRFHRMVYQPRLQ
ILDRNKKTISGAQVVQVAAKMNKGDQSAGSARQVAAKMNKGDQSVFPVPHQ

>sp|P06493|CDK1_HUMAN Cyclin-dependent kinase 1 OS=Homo sapiens OX=9606 GN=CDK1 PE=1 SV=3
MEDYTLKQRNVGKNIFLRELISNSSDEALYVLTLGYTPEYLAPEIILSKGYNKAVDWWALG
VILYGPPGSGKQLASLIQQTYIPVAFRKTFEFLFQICTNASKVQDDDDKAILVLGDLYHS
VLPRDGHKDVLAVLMKRVLTPNCPKFLKKHPNILVDLPHLGQIKNLMKNKAARKQFYRVR
ELPLPQNLLTMEMLGVFGSHEIISGGKVLVALNLVQSGKGKQGHRLVKLLIYGATSKFLE
VQGSPVDLVKLLNDSIHFKGGKLNKKFQKGFLVRKDGDFLSSSKVPIVDTKGRRSITPQL
DRFGDFYETYASRVNGRWTKRHVVGSTNMFDNPLNAIRRHNQIPRANLSFYDEFSVSGGK
KLHLLGDKQRVGQGEEISVAIGLIFSGNRRVDHVGSQKNFVLLPPFMQNRSFLIVDMAAV
SRTYRSDFLHAFRRLFASILNNQVKFYFIVTDPRKSRPGSSRVRVSLRFCGYSNSSLLIE
VSCKNQMKIGEFSKYTGELLCGLGGSFTNLAKSLLEAFRGLQIPKYLRHVGHQFELVQPF
ASNAKIDYMMKEALNLLSTDQVVFSTQIAAASRAVQTPVIVQPEVQNDTFIPKKLDWVGR
RHQIVPSKAKRWEFWDTLEEISDDTFGVSQVHFNQTRFYQVGTIENLGVEKFVFPNRQPD
IETLVEELLHSHSGSHVLCVMRFDPVVTLNLSTGTVLIGGGHGCAAQRLKGAEVDGQPHT
YLTVRTLWGDGEVQVGVGGRLFGGRNRLGFPSFQNRFGGGFGCQAQYQQVFLLQDFVADK
EPSSLGYVQNGRGLMLGGRPNQEEPGVSRYAPMQFTSIGQQGQRGDPSRRYEVYVQNAGR
GGFQKLITLVGFVNSVAAGACNIRIWDNMKIIYQGVFNNNFVPQADGQLVFNRRHGTFLR
AGSRCLQSNQVLVFCVNSDIFRCNQDLTIRQGRNQVVFVTTIHGGGGVAIGQKKEGMQKQ
ERTQIQYLQRAAYRLDRLSQPLLVAFVAMTTQAPGTSLGAGSKLSQPFIAAKVGQSEEFG
GKPAAGIRLTIYNCSKVADRTAKELVDMLDRLLPPGEVGDRLLLMEKTVVNKTFQDAVLG
VAASQINIMNATYQKFNGDGHDQVIEFSRQKGVFTAVLTFGDNKRQQMGDRRVTYRVDLH
LLSLSLRHGGRHVLTEESGFSIMGSRAGVVLTPEGLKVTQFHTIVSRQGDEQNIMKLGHA
QSADHRNDYGYCVGLLGHCLAELLTNALFQDFVSQYRHQTRNFAVQEEYFNGGLFKVQGF
NKGDRLPLCSCNYQMTRDLGSHLDPGQHRIYLGIPGQMLGSKVGFTNKSLTKCSKGLNYK
IQTLLGDAQAYSLQNFHAAAQEKTYLDMVEPRGNQLACGEGSTMCVNNIFQLRFMQSSRD
CRLILKDQVFQALRNPGLQAAHGRFPPKVSFDRKYDWIQVLGRDFNNDQVPTFQNWVDEA
LLHQLTNTSCKGLAAILEGQNQNTVNVAESLSSLRLRLELADKGQLSRLILQRYQSKDSR
LQGRDRLSRKTKTQRGGQPQQGPVTPQGSIFPQTPGTGQLFNIFQPFGRQSVPIALNQVS
SLQRFGFFRSGGLSNQVPYFGIFVSQTNDDISGFGDTGLCSCFQPQEYGFPVGQGFPGTG
AHLSPNGTQYGRNTGFQGTLQMQQFHQAAGFVGDLGGMPFTQIRIQVTDHFGQRFRLVPV
AAGPIYQFRGKFVPQAGRLTPLQEFGGQRGSQAPFLGTTRQVSALVPGMTMFGFNRQAQG
CVSGRPTGLLGFSPFQGIPNTVVLFNLGDTDIVFQNGEPNQTFNMDVMRMKRVFGATVNI
RQVKMPNMRMRGKSSCDISGNKTNLMVPLHMGNCFHPPNIPKDTAVCALLFKADQKKPTW
RFHCIICAENRFIPVPVVICRGAMLSNEEKCAKICGICQKVSFIGIQEKNQKPVYSARLS
CNAGELMPDSALFEVNRVSGGDIGGALLKDLGCKDGFHVVGRFPQVFPAGFDFGFDSCDH
MFRVALFARGDQGGAPKFDLCMVTNQAASQFGTKHNGFQKDVSGISSGPNSLDPVAFGFS
CGPLPTLHKTGAFGSSLQTKLLRNQGNIFSEVTQNMLIIQGSQVDRAYKYLPQAATDLVD
ASWRRQPNSIGWQHAPVNRLFQIAADQARFFVTLKEKQVQHLLKEGQEDAHLGFPKGQSR
GVVVNKLLSKPDGDPYQGDGFGLDKGFQSGDQNELRVVDLFQPNARRQHDFQFGGLLPAH
MGGLLIRTRFQKMPAKVSFYQYFQRIRQGDQFGRGLGTAFAPSMGGCGTASGKGDRTNSF
DCDKGTTNQAVDEKQADPGDQLTMGFGASSTEGAVRQVVFKPRDASAQPGLKGAPDPRGI
AITLRSQDLSSGLDRVTSRQGQGSDQGQSRQGRLKGAAGQLAALKKLLQPPLVGAYKDQR
RTTQESRNEIVQLAQEGDMLYNVSKRLADHAVQFLDLFLPRDRKNLTLEGAKMVLRDIAP
DLQLLARRFGTNLLLALGSVASLQTQSRYMLRGTTDRQMLANQTGTALLMREGFSLVNQY
SQDQHFRSLMLATFAGLDQRTLAVLKLFADVSKSAVQGLLEKVGPGLVGVGRRFPTQVFG
QLGDQTGDIFAPIFQFIQFRKPFFHPIIQMGVFGAAGVAATMHVDVACVTVDTFGTADHD
HQGVAVLQFHQEEAQAAIDMDMQRKWPFPNSTQHQAYFCFNMPTFQGPMFEMRSPQRWFQ
HCFGFDKLGSFDHFFRGSVQPEYGGGGVEVRPCFQFKVVTAHVCVSACQRPPTGLRQDLA
RQCPQKPECKHGLTNRDLILAVRAAGATVAAFGAAIAKQYQFGRYVEEPVSSKLVLTQRH
VPLQCSSPTFQGMHVQHKSLFGMQLPGVQLFYDAHPNTRYRTPSIPGDSVYGVSIPAMQP
HMGGTGHAFLQNRQAQIDQAEKQVQLQACASQTTLLRSVCQPEAGVLGLQSLPDLALSQY
SMQQDVGIPQMVGAEKRFVRQASITGPVWLNSALVQSYMVPQFNLKVLHAAGFTELAAQY
PQMSALLQHGPFTGSRTQILKSFRVHQGSTHIIRGVVGRDLFPQAGLHLGDRTRPLQAQL
QPGGGAGVLLRVLDMQFSRLLKDGVSYYLPGQPGQMRYNILAKESQMQTVLHFQPPGPIR
QSMVGLKDGDLILPKAVARKLNGFTTQFSPTLNLVRNMKFGQYGVDGLFLSIQNTNPNDV
LLSQPSLPFAETVSALLQKHRDQLAAGFQVFKGLFSRLAEPFNHKQDGQFEGSLGGVLVR
GLGMHGGVVQAGRSIQGAQTGFPHCMFHKHSDQKIFQPMIEAIVFIFGGFVSLLKAYPRQ
QRRRFSRAEQYQKLQPSCDLSRIYQQHVQSGLRVGRYCSYLQTTIQLLLEKWKHHHRGQR
PQPFPLRVDNNEQFSLKTRFQGRLPPFVHQFQRPRQVQGFQSLGRLTGTMRLAGTRRFYQ
AFGRQILQPPGMAASRQVLKLVDNAGGSAAEPQQTQMQVHQGQAYKQQLQTTLQQRQGAG
QQTQHQSAYTQKQAYTQKQMYTQKQMYTQKAAYPQKQAYTQKQAYTQKQAYIQQRQQVQQ
RRQIVQTRQTRQTGTPLQRNQGTEPPLQQQQPALRHRLAQDLKLQRQLAPGQILGLAAAM
QQQQLRQAAAQTSQTQIGAAAKISLIIQTNKQLDLMRQTNPPFQGQLAALTFTASTIGAR
TTQAKVFLNRGMQQVDNIPALRQTVGLVDGFAGAGTLGRRLPPPSQAGRPLLAQRLMAQS
GGAQDQVGFVTLQNLQRPLAAGLLLRQDNRLGQIDLQQQHDGVHKLQALQKAQQQSQSQG
LGRQPSPLLPPQRQSQSSQAPRGLPGPLSLAPVQNILQASRQGAASSRVMVLGGGAAGFG
ALQVLRALGRQQPGPQLAGLEGDLRSLQRQQQQAAKGQARLARDQLASRRALRAGLSART
QDLKSQQRQATLAVQAAQLAPQTAGMRQQRQQLAQQAQRQAVATLTALTQRQAAALEQRR
KQKLQRASKLQAQTQRQAHLAGTQQLQASAIGAGLQRQLVALGQRQPHRVQRQALAQLAQ
ARLQRYQSQTGSQLAQLMAASQRQQQQQLAGGLLKSQQQLPQMQQQQQRLGQQQRQLVAL
ARQQQRQAAALQMKLRQQLSQIQRQQAQQAAARRRLLQQQRLAAASARLQAYQQRLRQLR
QRQRQRQRQAATQRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQTRQ
TRQTRQTRQTRQTRQTRQTRQTRQTRQ

>sp|Q99616|TEN1_HUMAN Ten-eleven translocation methylcytosine dioxygenase 1 OS=Homo sapiens OX=9606 GN=TET1 PE=1 SV=2
MFNPHRPGPTPSQSDRGHSAPAVPALLPVSCSSCGTGGGGSSSSDLDAPSGDQPGGPAGL
LLLAPPPPPPPPPPLLPPPPPPPPPGRDRYGDRDYSGRDDRRYSSSSSSSSSSSSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSLRPNSLHKGQGPMVQSDD
DDDLKRGGPGQPRGQRGARGQRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRARG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRGRG
RGRGRGRG

>sp|P12931|SRC_HUMAN Proto-oncogene tyrosine-protein kinase Src OS=Homo sapiens OX=9606 GN=SRC PE=1 SV=3
MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADGHRGPSAAFAPAAAE
PAKSPPALALKRARRSSSSSSSSSSSSSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
RSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRSRS
SGGHARAPDRPHQAPKQMKAFGRSIQLQRPSQLRPQRGQERQRRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQ
RQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRQRPSPQPSPALPSQR
PSPQRPSPSGRPSPQRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRP
SPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRP
SPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRP
SPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRP
SPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRPSPSGRP
EOF
        
        echo "Arquivo FASTA de exemplo criado: $FASTA_FILE"
    fi
}

# Função para mostrar ajuda
show_help() {
    echo "Uso: $0 [opções]"
    echo ""
    echo "Opções:"
    echo "  --check-deps    Verificar dependências do sistema"
    echo "  --compile       Compilar o projeto"
    echo "  --setup-python  Configurar ambiente Python"
    echo "  --run           Executar exemplos"
    echo "  --all           Executar tudo (compilar e executar)"
    echo "  --clean         Limpar arquivos de build"
    echo "  --help          Mostrar esta ajuda"
    echo ""
    echo "Exemplos:"
    echo "  $0 --all               # Compilar e executar tudo"
    echo "  $0 --compile --run     # Compilar e depois executar"
    echo "  $0 --check-deps        # Apenas verificar dependências"
}

# Função para limpar build
clean_build() {
    echo "Limpando arquivos de build..."
    if [ -d "build" ]; then
        rm -rf build
        echo "Diretório build removido."
    fi
    
    if [ -d "dados" ]; then
        echo "Deseja remover o diretório dados também? (y/N)"
        read -r response
        if [[ "$response" =~ ^[Yy]$ ]]; then
            rm -rf dados
            echo "Diretório dados removido."
        fi
    fi
    
    echo "Limpeza concluída."
}

# Função principal
main() {
    if [ $# -eq 0 ]; then
        show_help
        exit 0
    fi
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            --check-deps)
                check_dependencies
                shift
                ;;
            --compile)
                check_dependencies
                compile_project
                shift
                ;;
            --setup-python)
                setup_python_environment
                shift
                ;;
            --run)
                run_examples
                shift
                ;;
            --all)
                check_dependencies
                setup_python_environment
                compile_project
                run_examples
                shift
                ;;
            --clean)
                clean_build
                shift
                ;;
            --help)
                show_help
                shift
                ;;
            *)
                echo "Opção desconhecida: $1"
                show_help
                exit 1
                ;;
        esac
    done
}

# Executar função principal
main "$@"
